Update Build-ksunext-12-SUSFS.yml

diff --git a/.github/workflows/Build-ksunext-12-SUSFS.yml b/.github/workflows/Build-ksunext-12-SUSFS.yml
--- a/.github/workflows/Build-ksunext-12-SUSFS.yml
+++ b/.github/workflows/Build-ksunext-12-SUSFS.yml
@@ -186,11 +186,11 @@ jobs:
          cd kernel_workspace
          export LTO=thin
          #./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ github.event.inputs.CPUD }} ${{ github.event.inputs.BUILD_METHOD }}
-         ./kernel_platform/build_with_bazel.py -t ${{ github.event.inputs.CPUD }} ${{ github.event.inputs.BUILD_METHOD }}
+         ### ./kernel_platform/build_with_bazel.py -t ${{ github.event.inputs.CPUD }} ${{ github.event.inputs.BUILD_METHOD }}
          ### ./kernel_platform/build_with_bazel.py --lto=full -t ${{ github.event.inputs.CPUD }} ${{ github.event.inputs.BUILD_METHOD }}
          
          #./kernel_platform/build_with_bazel.py --lto=full -t pineapple gki --jobs=$(nproc --all) --verbose_failures --config=stamp --user_kmi_symbol_lists=//msm-kernel:android/abi_gki_aarch64_qcom --ignore_missing_projects -o "$(pwd)/out" || { echo "Bazel build failed"; exit 1; }
-         ### ./kernel_platform/build_with_bazel.py --lto=full -t pineapple gki --jobs=$(nproc --all) --verbose_failures --config=stamp --user_kmi_symbol_lists=//msm-kernel:android/abi_gki_aarch64_qcom --ignore_missing_projects || { echo "Bazel build failed"; exit 1; }
+         ./kernel_platform/build_with_bazel.py --lto=full -t pineapple gki --jobs=$(nproc --all) --verbose_failures --config=stamp --user_kmi_symbol_lists=//msm-kernel:android/abi_gki_aarch64_qcom --ignore_missing_projects || { echo "Bazel build failed"; exit 1; }
       
       - name: Make AnyKernel3
         run: |
@@ -219,5 +219,5 @@ jobs:
       - name: Upload AnyKernel3
         uses: actions/upload-artifact@v4
         with:
-          name: ak3_${{ env.KSUVER }}_ci_bbr_thin_${{ github.event.inputs.FEIL }}
+          name: ak3_${{ env.KSUVER }}_ci_bbr_thick_${{ github.event.inputs.FEIL }}
           path: ./AnyKernel3/*
